[{"mjqjpqmgbljsphdztnvjfqwrcgsmlb" 7}
 {"bvwbjplbgvbhsrlpgdmjqwftvncz" 5}
 {"nppdvjthqldpwncqszvftbrmjlhg" 6}
 {"nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg" 10}
 {"zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw" 11}]
One ←

[{"mjqjpqmgbljsphdztnvjfqwrcgsmlb" 19}
 {"bvwbjplbgvbhsrlpgdmjqwftvncz" 23}
 {"nppdvjthqldpwncqszvftbrmjlhg" 23}
 {"nznrnfrfntjfmvfwmzdfjlvtqnbhcprsg" 29}
 {"zcfzfwzzqfrljwzlrfnpqdbhtmscgvjw" 26}]
Two ←
